# Generated by Django 2.1 on 2018-08-27 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordroot', models.CharField(max_length=255, verbose_name='词根')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容组合')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='图片')),
                ('video', models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='视频')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='问答问题')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='问答回答')),
                ('baike_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='百科标题')),
                ('baike_content', models.TextField(blank=True, null=True, verbose_name='百科内容')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键词')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='Baikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordroot_text', models.CharField(max_length=255, verbose_name='词根')),
                ('wordroot_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='词根id, 可空')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='爬取链接')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '百度百科',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.Categories', verbose_name='上级分类')),
            ],
            options={
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordroot_text', models.CharField(max_length=255, verbose_name='词根')),
                ('wordroot_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='词根id, 可空')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='爬取链接')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片链接')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '百度图片',
            },
        ),
        migrations.CreateModel(
            name='ScrapyLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='爬取链接')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面标题')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '爬虫日志',
            },
        ),
        migrations.CreateModel(
            name='ScrapyRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='爬取链接')),
                ('search_rules', models.CharField(blank=True, max_length=255, null=True, verbose_name='搜索爬取规则')),
                ('title_rules', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题爬取规则')),
                ('content_rules', models.CharField(blank=True, max_length=255, null=True, verbose_name='内容爬取规则')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '链接管理',
            },
        ),
        migrations.CreateModel(
            name='ScrapyTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_at', models.DateField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('start_time_at', models.TimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('task_cycle', models.IntegerField(choices=[('0', '按指定日期时间执行'), ('1', '按指定时间每天执行'), ('2', '按指定时间每周执行'), ('3', '按指定时间每月执行')], default=0, verbose_name='定时方式')),
                ('is_done', models.IntegerField(choices=[('0', '否'), ('1', '是')], default=0, verbose_name='是否包含已采集')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '爬虫任务',
            },
        ),
        migrations.CreateModel(
            name='TagMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '标签管理',
            },
        ),
        migrations.CreateModel(
            name='Wordroots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='词语')),
                ('is_done', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否采集')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.Categories', verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '词库管理',
            },
        ),
        migrations.CreateModel(
            name='Youkus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordroot_text', models.CharField(max_length=255, verbose_name='词根')),
                ('wordroot_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='词根id, 可空')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='爬取链接')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='视频分享地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '优酷视频',
            },
        ),
        migrations.CreateModel(
            name='Zhidaos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordroot_text', models.CharField(max_length=255, verbose_name='词根')),
                ('wordroot_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='词根id, 可空')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='爬取链接')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '百度知道',
            },
        ),
        migrations.AddField(
            model_name='tagmaps',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.Tags'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.Categories', verbose_name='分类名称'),
        ),
    ]
